sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=full
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
cache: cargo
